### ISSUE TITLE
Problems when winning the game

### ISSUE THREAD

**Issue by kaenganxt** [MrBran4/SET-Challenge-2019#20]
Hello, greetings from Germany :)

**Describe the bug**
There are two problems when winning a game:
- When all missiles were destroyed: There are no statistics printed at the end of the log which breaks our testing Framework
- When at least one missile has hit the ship, but the rest of the missiles were destroyed: The game doesn't end and runs forever

**To Reproduce**
For the first: Destroy all Missiles
For the second: Use a Scenario that contains a single line like `SPAWN 1 20 2000 499`

**Expected behavior**
First: The simulator should always print the statistics
Second: The simulator should end after all missiles were destroyed or have hit the ship

**Environment**
 - OS: Windows 7 / Ubuntu
 - Simulator Version: v1.2

Thank you!

**Comment by dst8** [comment]
Sorry for the slow response on this, will get @MrBran4 to look into it.

**Comment by dst8** [comment]
Fixed in Version 1.2.1 - will be integrated into Finals Day software version too.
